{
 "title": "PC CQC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Seasons in selected timeframe",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\r\n  *, end_date - now() as expire_time, (start_date - $__timeFrom()) as \"Season will start regarding lower time bound\", (end_date - $__timeTo()) as \"Season will end regarding upper time bound\"\r\nfrom seasons\r\nWHERE \"start_date\" <= $__timeTo() AND \"end_date\" >= $__timeFrom();"
    }
   ]
  },
  {
   "title": "CQC PC activity heatmap",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "PC CQC Activity",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "with action_ids as (\r\n    select action_id, timestamp\r\n    from squads_stats_states_action_info\r\n    where\r\n        leaderboard_type = 'cqc' and\r\n        platform = 'PC' and\r\n        $__timeFilter(timestamp)\r\n    order by action_id desc\r\n    ),\r\n\r\n    sum_history as (\r\n        select sum(score) as sum_score, squads_stats_states_data.action_id as action_id, action_ids.timestamp as timestamp\r\n        from squads_stats_states_data, action_ids\r\n        where squads_stats_states_data.action_id = action_ids.action_id\r\n        group by squads_stats_states_data.action_id, action_ids.timestamp\r\n    ),\r\n\r\n    sum_history_old_calculated as (select\r\n        sum_score,\r\n        min(timestamp) as timestamp,\r\n        action_id,\r\n        lag (sum_score, 1) over (order by action_id) sum_score_old\r\n    from sum_history\r\n    group by sum_score, action_id\r\n    order by timestamp desc\r\n    )\r\n\r\nselect\r\n    max(sum_score::bigint) as sum_score,\r\n    max(action_id::bigint) as \"action_id\",\r\n    min(justify_interval(date_trunc('seconds', now() - timestamp))) as \"interval\",\r\n    $__timeGroup(timestamp, $__interval),  -- timestamp as time,\r\n    sum(sum_score - sum_score_old)::bigint as \"diff\"\r\nfrom sum_history_old_calculated\r\nwhere (sum_score - sum_score_old) <> 0\r\ngroup by time\r\norder by time;"
    }
   ]
  },
  {
   "title": "Active squadrons",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 6 },
   "targets": [
    {
     "rawSql": "select (select tag from squads_stats_states_data where squadron_id = squad_id limit 1) as tag, diff as points_gained\r\nfrom\r\n  (\r\n    select squadron_id as squad_id, sum(diff) as diff  -- squadron_id as squad_id because we need to avoid same column name in tag resolving subquery\r\n    from (\r\n      select \r\n        coalesce(high_lb.squadron_id, low_lb.squadron_id) as squadron_id, \r\n        high_lb.score - coalesce(low_lb.score, 0) as diff\r\n      from (\r\n        select *\r\n        from squads_stats_states_data\r\n        where action_id = (select min(action_id) as low from squads_stats_states_action_info where $__timeFilter(timestamp) and leaderboard_type = 'cqc' and platform = 'PC')\r\n  ) low_lb \r\n    full join (\r\n    select *\r\n    from squads_stats_states_data\r\n    where action_id = (select max(action_id) as low from squads_stats_states_action_info where $__timeFilter(timestamp) and leaderboard_type = 'cqc' and platform = 'PC')\r\n  ) high_lb\r\n  on high_lb.squadron_id = low_lb.squadron_id\r\n  where high_lb.score - coalesce(low_lb.score, 0) <> 0\r\n) without_grouping\r\ngroup by squadron_id\r\norder by diff desc) without_names;\r\n"
    }
   ]
  },
  {
   "title": "Active + top squadrons points",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "rawSql": "select tag as metric, score, timestamp as time\r\nfrom squads_stats_states_data \r\n  right join squads_stats_states_action_info\r\n    on squads_stats_states_action_info.action_id = squads_stats_states_data.action_id\r\nwhere $__timeFilter(timestamp) and platform = 'PC' and leaderboard_type = 'cqc'\r\nand squadron_id in\r\n(select squadron_id as squad_id  -- squadron_id as squad_id because we need to avoid same column name in tag resolving subquery\r\n    from (\r\n      select \r\n        coalesce(high_lb.squadron_id, low_lb.squadron_id) as squadron_id, \r\n        high_lb.score - low_lb.score as diff\r\n      from (\r\n        select *\r\n        from squads_stats_states_data\r\n        where action_id = (select min(action_id) as low from squads_stats_states_action_info where $__timeFilter(timestamp) and leaderboard_type = 'cqc' and platform = 'PC')\r\n  ) low_lb \r\n    full join (\r\n    select *\r\n    from squads_stats_states_data\r\n    where action_id = (select max(action_id) as low from squads_stats_states_action_info where $__timeFilter(timestamp) and leaderboard_type = 'cqc' and platform = 'PC')\r\n  ) high_lb\r\n  on high_lb.squadron_id = low_lb.squadron_id\r\n  where high_lb.score - coalesce(low_lb.score, 0) <> 0 or high_lb.\"rank\" < 3  -- Given rank stored from zero included\r\n) without_grouping\r\ngroup by squadron_id)\r\norder by timestamp;"
    }
   ]
  },
  {
   "title": "PC CQC Activity but it's not table",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "with action_ids as (\r\n    select action_id, timestamp\r\n    from squads_stats_states_action_info\r\n    where\r\n        leaderboard_type = 'cqc' and\r\n        platform = 'PC' and\r\n        $__timeFilter(timestamp)\r\n    order by action_id desc\r\n    ),\r\n\r\n    sum_history as (\r\n        select sum(score) as sum_score, squads_stats_states_data.action_id as action_id, action_ids.timestamp as timestamp\r\n        from squads_stats_states_data, action_ids\r\n        where squads_stats_states_data.action_id = action_ids.action_id\r\n        group by squads_stats_states_data.action_id, action_ids.timestamp\r\n    ),\r\n\r\n    sum_history_old_calculated as (select\r\n        sum_score,\r\n        min(timestamp) as timestamp,\r\n        action_id,\r\n        lag (sum_score, 1) over (order by action_id) sum_score_old\r\n    from sum_history\r\n    group by sum_score, action_id\r\n    order by timestamp desc\r\n    )\r\n\r\nselect\r\n    $__timeGroup(timestamp, $__interval),  -- timestamp as time,\r\n    sum(sum_score - sum_score_old)::bigint as \"diff\"\r\nfrom sum_history_old_calculated\r\nwhere (sum_score - sum_score_old) <> 0\r\ngroup by time\r\norder by time;"
    }
   ]
  }
 ]
}