{
 "title": "WRYR",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \"timestamp\" as time, score, \"rank\"\r\nfrom squads_stats_states_data\r\n  right join squads_stats_states_action_info\r\n    on squads_stats_states_data.action_id = squads_stats_states_action_info.action_id\r\nwhere squadron_id = 47999 and leaderboard_type = 'aegis' and $__timeFilter(\"timestamp\")\r\norder by \"timestamp\";"
    }
   ]
  },
  {
   "title": "BGS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select \"timestamp\" as time, score, \"rank\"\r\nfrom squads_stats_states_data\r\n  right join squads_stats_states_action_info\r\n    on squads_stats_states_data.action_id = squads_stats_states_action_info.action_id\r\nwhere squadron_id = 47999 and leaderboard_type = 'bgs' and $__timeFilter(\"timestamp\")\r\norder by \"timestamp\";"
    }
   ]
  },
  {
   "title": "COMBAT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select \"timestamp\" as time, score, \"rank\"\r\nfrom squads_stats_states_data\r\n  right join squads_stats_states_action_info\r\n    on squads_stats_states_data.action_id = squads_stats_states_action_info.action_id\r\nwhere squadron_id = 47999 and leaderboard_type = 'combat' and $__timeFilter(\"timestamp\")\r\norder by \"timestamp\";"
    }
   ]
  },
  {
   "title": "EXPLORATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select \"timestamp\" as time, score, \"rank\"\r\nfrom squads_stats_states_data\r\n  right join squads_stats_states_action_info\r\n    on squads_stats_states_data.action_id = squads_stats_states_action_info.action_id\r\nwhere squadron_id = 47999 and leaderboard_type = 'exploration' and $__timeFilter(\"timestamp\")\r\norder by \"timestamp\";"
    }
   ]
  },
  {
   "title": "TRADE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select \"timestamp\" as time, score, \"rank\"\r\nfrom squads_stats_states_data\r\n  right join squads_stats_states_action_info\r\n    on squads_stats_states_data.action_id = squads_stats_states_action_info.action_id\r\nwhere squadron_id = 47999 and leaderboard_type = 'trade' and $__timeFilter(\"timestamp\")\r\norder by \"timestamp\";"
    }
   ]
  },
  {
   "title": "CQC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select \"timestamp\" as time, score, \"rank\"\r\nfrom squads_stats_states_data\r\n  right join squads_stats_states_action_info\r\n    on squads_stats_states_data.action_id = squads_stats_states_action_info.action_id\r\nwhere squadron_id = 47999 and leaderboard_type = 'cqc' and $__timeFilter(\"timestamp\")\r\norder by \"timestamp\";"
    }
   ]
  },
  {
   "title": "POWERPLAY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "select \"timestamp\" as time, score, \"rank\"\r\nfrom squads_stats_states_data\r\n  right join squads_stats_states_action_info\r\n    on squads_stats_states_data.action_id = squads_stats_states_action_info.action_id\r\nwhere squadron_id = 47999 and leaderboard_type = 'powerplay' and $__timeFilter(\"timestamp\")\r\norder by \"timestamp\";"
    }
   ]
  },
  {
   "title": "Historical general data",
   "type": "table",
   "description": "These data are fetched around one time per week.\nNot time filterable.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "queryText": "select\n       squad_id,\n       name,\n       tag,\n       owner_name,\n       created,\n       accepting_new_members,\n       power_name,\n       superpower_name,\n       faction_name,\n       user_tags,\n       member_count,\n       current_season_trade_score,\n       previous_season_trade_score,\n       current_season_combat_score,\n       previous_season_combat_score,\n       current_season_exploration_score,\n       previous_season_exploration_score,\n       current_season_cqc_score,\n       previous_season_cqc_score,\n       current_season_bgs_score,\n       previous_season_bgs_score,\n       current_season_powerplay_score,\n       previous_season_powerplay_score,\n       current_season_aegis_score,\n       previous_season_aegis_score,\n       motd,\n       author,\n       \"date\" as \"motd_date\",\n       squadrons_historical_data.operation_id as operation_id,\n       \"timestamp\" as updated\nfrom squadrons_historical_data\n    inner join operations_info oi\n        on oi.operation_id = squadrons_historical_data.operation_id\n    left join squadrons_news_historical snh\n        on oi.operation_id = snh.operation_id\nwhere squad_id = 47999\norder by \"timestamp\" desc;",
     "rawQueryText": "select\n       squad_id,\n       name,\n       tag,\n       owner_name,\n       created,\n       accepting_new_members,\n       power_name,\n       superpower_name,\n       faction_name,\n       user_tags,\n       member_count,\n       current_season_trade_score,\n       previous_season_trade_score,\n       current_season_combat_score,\n       previous_season_combat_score,\n       current_season_exploration_score,\n       previous_season_exploration_score,\n       current_season_cqc_score,\n       previous_season_cqc_score,\n       current_season_bgs_score,\n       previous_season_bgs_score,\n       current_season_powerplay_score,\n       previous_season_powerplay_score,\n       current_season_aegis_score,\n       previous_season_aegis_score,\n       motd,\n       author,\n       \"date\" as \"motd_date\",\n       squadrons_historical_data.operation_id as operation_id,\n       \"timestamp\" as updated\nfrom squadrons_historical_data\n    inner join operations_info oi\n        on oi.operation_id = squadrons_historical_data.operation_id\n    left join squadrons_news_historical snh\n        on oi.operation_id = snh.operation_id\nwhere squad_id = 47999\norder by \"timestamp\" desc;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}